---
title: "List Experiment and Racial Prejudice"
output:
  html_document: default
  pdf_document: default
---

Despite the legal end of desegregation in the United States South,
racial tension persists. While outright discrimination against
African-Americans is illegal, some believe that many white Southerners
continue to be prejudiced against blacks at higher rates than whites
in the rest of the United States. Others have suggested that, during
the 1970s and 1980s, a 'new South' emerged, in which racial tensions
declined and the attitudes of white Southerners came to closely mirror
the rest of the country. Because of the sensitive nature of racial
prejudice, however, asking respondents directly about their feelings
towards blacks is likely to elicit untruthful answers from some
people. To get around this, researchers used a list experiment to
estimate the proportion of respondents who exhibit racial prejudice.
We saw the application of list experiment in
Section 3.1 where it was used to measure support
for combatants among Afghan citizens.  Readers are encouraged to read
that section before they begin this exercise.

In the 1991 National Race and Politics survey, researchers randomly
divided respondents into two groups.  Those assigned to the control
condition were read the following script: 

> Now, I am going to read you three things that sometimes make people angry or upset. After I read all three, just tell me HOW MANY of them upset you. I don't want to know which ones, just HOW MANY.
>
> - The federal government increasing the tax on gasoline
> - Professional athletes getting million-dollar contracts
> - Large corporations polluting the environment

Those respondents assigned to the treatment group, on the other hand,
received the same script except that the list included one additional
item that read 'a black family moving in next door.' The data set we
will be analyzing for this exercise is contained in the csv file
*listexp.csv*. The names and descriptions of the variables
in this data set are listed in the table below.

------------------------------------------------------------------------------
 Name                Description
 ------------------- ---------------------------------------------------------
 `id`                Unique id of the respondent
 
 `y`                 The number of items selected from the list
 
 `treat`             The treatment indicator (binary)
 
 `south`             An indicator for residence in a Southern state
------------------------------------------------------------------------------

## Question 1

Begin by computing the overall proportion of respondents who
  demonstrate racial prejudice and the standard error of this estimate. 

 For now, remove all observations for
  which there are missing values on the outcome variable. 
  

### Question 2

 Compute the 90%, 95% and 99% confidence interval for this estimate.  
 Give a brief interpretation of the result.  
 
 
## Question 3

  Now do the same thing (compute sample proportion and standard error)
  separately for Southern and non-Southern respondents. 
  
  Calculate the confidence intervals separately for each, as well as the z-scores.
  

## Question 4

Construct the 95 percent confidence interval for the
  difference in the population proportion of those who are prejudiced
  between the South and non-Southern whites.  Interpret the result.
  
## Question 5

A critical assumption of the list experiment is that the
  inclusion of the sensitive item does not alter the respondents'
  willingness to give a truthful answer to the number of items that
  upset them.  Test this assumption by examining the rates of
  non-response. 
  
  Compare the Southern and non-Southern subsets.  Are
  there differences between the Southern and non-Southern respondents?
  What does this tell us about the validity of the list experiment and
  racial attitudes between the regions?
  




##### EXTRA

## Question 6

Now we conduct randomization inference separately for the South
  and non-South samples. Using the difference-in-means estimator as a
  test statistic, simulate the randomization distribution for 10,000
  possible treatment assignments under the null hypothesis that the
  population proportion of those who are racially prejudiced is zero.
  For both the South and non-South samples, create a histogram of this
  randomization distribution and include as a vertical line the actual
  estimated proportion. Then, use these distributions to approximate
  the one-sided $p$-values and conduct the hypothesis test using 0.05 as the
  threshold of statistical significance.  Provide a brief interpretation 
  of the result.
  
  